junit_tests(
	name = "CubeCalculatorTest",
	sources = ["src/test/scala/CubeCalculatorTest.scala"],
	dependencies = [":CubeCalculator"]
)

scala_library(
	name = "CubeCalculator",
	sources = ["src/main/scala/CubeCalculator.scala"],
)